[env]
SPRING_PROFILES_ACTIVE = 'local'
AWS_PROFILE = "oph-ktr-dev"

[tools]
node = "22.18.0"
"npm:prettier" = "3.6.2"
"aqua:maven" = "3.9.11"
java = "corretto-21.0.8.9.1"
shellcheck = "0.11.0"
ktlint = "1.7.1"
go = "1.25.0"
"npm:esbuild" = "0.25.9"
"go:github.com/humanlogio/humanlog/cmd/humanlog" = "0.8.8"
"ubi:karlderkaefer/cdk-notifier" = "2.14.6"
aws-cli = "2.28.11"
"aqua:aws/session-manager-plugin" = { version = "1.2.707", os = ["macos"] }
