[env]
SPRING_PROFILES_ACTIVE = 'local'
AWS_PROFILE = "oph-ktr-dev"

[tools]
node = "24.12.0"
"npm:prettier" = "3.7.4"
"aqua:maven" = "3.9.11"
java = "corretto-25.0.1"
shellcheck = "0.11.0"
ktlint = "1.8.0"
go = "1.25.5"
"npm:esbuild" = "0.27.2"
"go:github.com/humanlogio/humanlog/cmd/humanlog" = "0.8.9"
"ubi:karlderkaefer/cdk-notifier" = "2.14.10"
aws-cli = "2.32.32"
"aqua:aws/session-manager-plugin" = { version = "1.2.707", os = ["macos"] }
