[env]
SPRING_PROFILES_ACTIVE = 'local'
AWS_PROFILE = "oph-ktr-dev"

[tools]
node = "24.11.0"
"npm:prettier" = "3.6.2"
"aqua:maven" = "3.9.11"
java = "corretto-25.0.1"
shellcheck = "0.11.0"
ktlint = "1.7.1"
go = "1.25.3"
"npm:esbuild" = "0.25.12"
"go:github.com/humanlogio/humanlog/cmd/humanlog" = "0.8.9"
"ubi:karlderkaefer/cdk-notifier" = "2.14.6"
aws-cli = "2.31.27"
"aqua:aws/session-manager-plugin" = { version = "1.2.707", os = ["macos"] }
